poanetwork/hbbft

src/agreement.rs
src/common_subset.rs
tests/agreement.rs
tests/common_subset.rs

I've updated the BA and ACS modules so that BA is now an instance of `DistAlgorithm`. I also modified one of the BA tests to test for termination when more than 2/3 nodes propose.

The BA module now defines a DistAlgorithm instance

---

Cargo.toml
src/agreement.rs
src/common_subset.rs
src/honey_badger.rs
src/lib.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_subset.rs
tests/honey_badger.rs
tests/network/mod.rs

Verify termination and more outputs.
`CommonSubset` now instantiates `Agreement` with the correct ID.

Extend tests and fix CommonSubset.

---

.travis.yml
Cargo.toml
examples/network/node.rs
src/crypto/error.rs
src/crypto/mod.rs
src/lib.rs

Implement threshold signatures and encryption.

---

src/agreement/mod.rs
src/broadcast.rs
src/common_subset.rs

Change some of the error handling according to #24.

Make Broadcast handle large payloads, change some errors.

---

.travis.yml
examples/consensus-node.rs
examples/network/node.rs
examples/simulation.rs
proto/message.proto
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/crypto/mod.rs
src/crypto/protobuf_impl.rs
src/honey_badger.rs
src/lib.rs
src/messaging.rs
src/proto/mod.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_coin.rs
tests/common_subset.rs
tests/honey_badger.rs
tests/network/mod.rs

Close #39 
This might also require a further commit to solve a few merge conflicts after we merge #58.

Common coin

---

examples/simulation.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/honey_badger.rs
src/messaging.rs
tests/honey_badger.rs

Also, consistently name generic arguments, and remove some unused trait
bounds.

Return proposer info from HoneyBadger.

---

README.md

- Reorganized - moved extemporaneous info towards the bottom of the doc
- Added --release flag to network example
- Added Test heading with --release flag instruction
- Added Coin algorithm optimization using a schedule to Current TODOS

README re-organization and additions

---

README.md
examples/simulation.rs
src/common_coin.rs
src/crypto/mod.rs
src/crypto/poly.rs
src/crypto/protobuf_impl.rs
src/crypto/serde_impl.rs
src/lib.rs
src/messaging.rs
src/sync_key_gen.rs
tests/broadcast.rs
tests/network/mod.rs
tests/sync_key_gen.rs

This is a _synchronous_ key generation algorithm. We will use it in
`DynamicHoneyBadger`, on top of `HoneyBadger` to satisfy the synchrony
requirements.
It can also be used independently e.g. on top of a blockchain.
The generic arguments are removed from the cryptography types.
Closes #71

Implement SyncKeyGen.

---

src/honey_badger.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_coin.rs
tests/common_subset.rs
tests/honey_badger.rs
tests/network/mod.rs

An adversary sending faulty decryption shares

---

tests/honey_badger.rs

Output sequence verification in HoneyBadger test

---

src/broadcast.rs

Also replaces the word "good" with "correct".

Move broadcast docs to module-level.

---

src/agreement/mod.rs
tests/common_subset.rs
tests/honey_badger.rs

This is a first step towards #113.

Fix Subset for a single validator.

---

src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/change.rs
src/dynamic_honey_badger/err.rs
src/dynamic_honey_badger/mod.rs

This doesn't change the implementation. It just splits up the module into several files.

Split the dynamic_honey_badger module.

---

.travis.yml
src/crypto/poly.rs

- Added `impl Drop for Poly` which fills the `coeff` vector with `Fr::zero()`.
- Added `impl Drop for BivarPoly` which fills the `coeff` vector with `Fr::zero()` and resets the `degree`.
Closes Issue #139

Clear 'SecretKeySet' on drop.

---

examples/network/node.rs
examples/simulation.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/mod.rs
src/honey_badger.rs
src/messaging.rs
src/queueing_honey_badger.rs
tests/broadcast.rs
tests/dynamic_honey_badger.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs

Close #149 
This branch is currently WIP since the tests of `DynamicHoneyBadger` and `QueueingHoneyBadger` don't pass.

Outgoing message API refactoring

---

src/crypto/mod.rs
src/honey_badger.rs
src/messaging.rs

Remove output and message queue from HoneyBadger.

---

Cargo.toml
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/honey_badger.rs
src/lib.rs
src/messaging.rs
src/queueing_honey_badger.rs
src/sync_key_gen.rs

Remove queue fields from Agreement, CommonCoin, Broadcast and CommonSubset.

---

src/broadcast.rs

Close #135 
Please feel free to critisize if you think the example can be improved.

Updated the Broadcast doc example to the latest API

---

src/agreement/mod.rs

* Call `on_bin_values_changed` even if there is only one value.
* Handle the case _f = 0_ correctly: `count_bval` can be equal to both
_f + 1_ and _2 f + 1_.

Fix bin_values change handling in agreement.

---

src/agreement/mod.rs

I wonder what you think about this small change.

Avoids cloning of Agreement::received_term

---

src/agreement/mod.rs

Also, don't bother updating the epoch after we've terminated.

Make sure Term messages are handled as BVal, Aux, Conf.

---

examples/network/node.rs
src/agreement/agreement.rs
src/agreement/mod.rs
src/broadcast/broadcast.rs
src/broadcast/error.rs
src/broadcast/mod.rs
src/common_subset.rs
tests/broadcast.rs

Also, rename broadcast and agreement messages to just `Message`.

Split up the broadcast module.

---

.travis.yml

Fix build if secure env vars are unavailable.

---

Cargo.toml
tests/README.md
tests/net/adversary.rs
tests/net/mod.rs
tests/net/proptest.rs
tests/net_dynamic_hb.rs
tests/net_util.rs

This PR creates the first `proptest` based test, using a strategy to grow and shrink network topologies (strategies are used to generate random instances of these). It includes a number of additional manual debug implementations as well.

Network dimension strategy for property based tests.

---

.travis.yml
tests/net/proptest.rs
tests/net_dynamic_hb.rs

Disable beta, use `stable` channel.

---

README.md

Mention Rust version in `README.md`.

---

.travis.yml
ci.sh

Bringing it in line with `threshold_crypto`.

Factored out CI execution into `ci.sh`.

---

.travis.yml
ci.sh

Adds a `cargo audit` to the CI.

Added `cargo audit` to CI.

---

src/dynamic_honey_badger/builder.rs
src/honey_badger/builder.rs

This is a basic tool for starting `HoneyBadger` instances in non-trivial epochs as suggested by @afck in https://github.com/poanetwork/hbbft/issues/226#issuecomment-421761224.
Closes #275

Allowed building a HB with a non-0 starting epoch

---

src/honey_badger/epoch_state.rs

Profiling the simulation example (with mock crypto) identified this as a hot spot, and using a `Vec` instead and returning early where possible speeds it up.

Avoid BTreeMap in EpochState.

---

tests/README.md
tests/net/mod.rs

Saves valuable harddrive space!

Changed the defaults for tracing to `false`.

---

Cargo.toml

Also: Follow the soon-to-be-official formatting guidelines:
https://github.com/nrc/rfcs/blob/style-guide/style-guide/cargo.md

Use published threshold_crypto 0.2.

---

tests/network/mod.rs

This feature allows `EpochStarted` sender queue messages sent by the observer to be received by other nodes.

Allow the observer on a TestNetwork to send messages

---

src/traits.rs

These doc additions capture what we currently consider best practices when handling algorithm output.

Include advice on how to handle `Step` in docs.

---

src/binary_agreement/binary_agreement.rs
src/broadcast/broadcast.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/fault_log.rs
src/honey_badger/epoch_state.rs
src/subset.rs
src/sync_key_gen.rs
src/threshold_sign.rs

Remove redundant log statements, minor cleanups.

---

src/broadcast/mod.rs

* Reorganize the explanation, separate algorithm from justification.
* Some of the message numbers were wrong.
* Use `[i]` for indices, even in pseudocode.

Improve the broadcast documentation.

---

examples/simulation.rs
src/binary_agreement/binary_agreement.rs
src/binary_agreement/mod.rs
src/binary_agreement/sbv_broadcast.rs
src/broadcast/broadcast.rs
src/dynamic_honey_badger/mod.rs
src/honey_badger/epoch_state.rs
src/honey_badger/honey_badger.rs
src/lib.rs
src/queueing_honey_badger/mod.rs
src/sender_queue/dynamic_honey_badger.rs
src/sender_queue/mod.rs
src/sender_queue/queueing_honey_badger.rs
src/subset/proposal_state.rs
src/subset/subset.rs
src/threshold_decrypt.rs
src/threshold_sign.rs
src/traits.rs
tests/binary_agreement_mitm.rs
tests/net/adversary.rs
tests/net/mod.rs
tests/network/mod.rs

Make Step independent of DistAlgorithm.

---

src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/queueing_honey_badger/mod.rs
src/sender_queue/dynamic_honey_badger.rs
src/sender_queue/honey_badger.rs
src/sender_queue/message.rs
src/sender_queue/mod.rs
src/sender_queue/queueing_honey_badger.rs
src/traits.rs
tests/honey_badger.rs

Simplify the sender queue.

---

src/broadcast/mod.rs
src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/fault_log.rs
src/honey_badger/batch.rs
src/honey_badger/builder.rs
src/honey_badger/epoch_state.rs
src/honey_badger/error.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/honey_badger/params.rs
tests/honey_badger.rs

Remove the random_value option.

---

README.md

Added medium post on threshold cryptography

Added medium post on threshold cryptography to README.md

---

.travis.yml
Cargo.toml
examples/network/node.rs
examples/simulation.rs
hbbft_testing/src/lib.rs
src/broadcast/broadcast.rs
src/broadcast/mod.rs
src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/change.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/error.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/honey_badger/honey_badger.rs
src/lib.rs
src/network_info.rs
src/sender_queue/dynamic_honey_badger.rs
src/subset/proposal_state.rs
src/sync_key_gen.rs
tests/broadcast.rs
tests/dynamic_honey_badger.rs
tests/queueing_honey_badger.rs
tests/sync_key_gen.rs

Remove NetworkInfo from Broadcast and keys from NetworkInfo.

---

src/sync_key_gen.rs

It uses default arguments so that existing code does not need to be changed.

Make non-threshold crypto in SyncKeyGen pluggable.

---

src/threshold_sign.rs
tests/threshold_sign.rs

Add a test that actually verifies the signature, and refactor the tests a bit.

Clean up threshold sign tests.
