src/broadcast/mod.rs
src/messaging.rs
src/node.rs
src/proto/mod.rs
tests/broadcast.rs
tests/netsim.rs
tests/node_comms/mod.rs

This adds a length byte to the values before padding with 0, so that we
can omit the padding at the end again. Shards are not converted to the
type parameter `T` anymore, because they are not necessarily valid
representations of a `T` value, e.g. valid UTF-8, as in the tests.
It also shortens some debug messages by printing byte arrays as
hexadecimal, and eliding some bytes.
One of the files in `tests` is moved to a subdirectory, so it's not considered a test target itself by cargo.

Make tests compile, fix value encoding, shorten debug messages.

---

.travis.yml
Cargo.toml
examples/consensus-node.rs
examples/network/commst.rs
examples/network/connection.rs
examples/network/messaging.rs
examples/network/node.rs
examples/run-consensus-nodes.sh
src/broadcast.rs
src/common_subset.rs
src/messaging.rs
src/proto/mod.rs
src/proto_io.rs
tests/broadcast.rs

This fixes several issues with the broadcast algorithm and enables the
previously ignored tests that now pass:
* Don't decide on a root hash based on anyone's `Echo` message.
* Work around the `merkle` crate's inability to produce the proof of the
`i`-th leaf for a given index `i`.
* Ignore messages from unknown nodes.
* Avoid decoding multiple times.
* Document the full algorithm.
* Don't count multiple `Echo` or `Ready` messages coming from the same
node.
* Fix index computation for a given proof.
* Move `BroadcastMessage` into `broadcast` to make the module more
self-contained.
The example now only executes a single broadcast instance, expecting the
first node (the one with the lexicographically lowest address) to
propose a value. A shell script is added that runs for example nodes. …

Fix broadcast and example, enable more tests.

---

Cargo.toml
TODO
proto/message.proto
src/agreement.rs
src/common_subset.rs
src/lib.rs
src/proto/mod.rs

I've defined the ACS algorithm and an interface to it consisting of 3 functions: new, send_proposed_value and on_input. The latter is a message handler for RB and BA messages. These two types of message are therefore joined in the types of message inputs and outputs.
Note about BA: A common coin implementation is not provided in this pull request. The coin value is constant 1 at https://github.com/poanetwork/hbbft/blob/15353e8d27398fa745a99a148f74276c62ec1d11/src/agreement.rs#L174.

The ACS and BA algorithms

---

src/agreement.rs
tests/agreement.rs
tests/broadcast.rs

This pull request adds a simple test module of Binary Agreement. There is no notion of adversary at the moment. Asynchrony between BA instances is not modelled yet either.

Binary Agreement test module

---

examples/network/node.rs
src/agreement.rs
src/broadcast.rs
src/common_subset.rs
src/honey_badger.rs
src/messaging.rs
src/proto/mod.rs
tests/broadcast.rs

This will allow us to deduplicate network simulations in tests for the
different algorithms. More generally, it facilitates writing general
tools and applying them to all distributed algorithms.

Define a common DistAlgorithm trait.

---

src/agreement.rs
src/common_subset.rs
src/honey_badger.rs
tests/common_subset.rs

The Common Subset output is changed from a set of proposed values into a map from node IDs to proposed values. In `src/agreement.rs`, AUX messages are now guaranteed to be sent once an epoch.

Common Subset test and fixes

---

Cargo.toml
examples/network/commst.rs
src/agreement.rs
src/broadcast.rs
src/common_subset.rs
src/honey_badger.rs
src/lib.rs
src/proto_io.rs

Changed error handling from using `enum Error`'s to using the `error-chain` crate.
*Note:* the following lines in `Cargo.toml`
```
reed-solomon-erasure = { git = "https://github.com/darrenldl/reed-solomon-erasure.git", branch = "dev" }
```
should be changed to
```
reed-solomon-erasure = "<NEW VERSION NUMBER>"
```
to reflect (the soon to be published to crates.io) version bump for `reed-solomon-erasure`.
The `dev` branch in `reed-solomon-erasure` currently contains changes that implement`std::error::Error` for `reed-solomon-erasure::Error`. These changes are required by this PR.

Added error-chain error handling.

---

proto/message.proto
src/agreement.rs
src/agreement/bin_values.rs
src/agreement/mod.rs
src/proto/mod.rs

In order to guarantee termination, the common coin is invoked in the CONF round only for the subset of `bin_values` committed to in the CONF message. The Cobalt fix used the whole set of `bin_values`, which led to non-termination in our tests.

Added a CONF round

---

proto/message.proto
src/agreement/mod.rs
src/proto/mod.rs

Close #55 
A terminated instance continues handling messages after termination according to the previous semantics of termination. However a `Term` message is sent only once.

Added Term messages in Agreement and enabled early termination

---

src/crypto/mod.rs
src/crypto/poly.rs

This adds a `Hash` implementation for public keys, commitments,
ciphertexts and signatures — types that might make sense to be included
in special transactions. The `DynamicHoneyBadger` implementation will
require some of them.

Implement Hash for "public" cryptographic types.

---

Cargo.toml
src/crypto/mod.rs
src/lib.rs
src/messaging.rs

- Changed `NetworkInfo` to use `ClearOnDrop<Box<SecretKey<Bls12>>>`.
- Changed `SecretKeySet.secret_key_share()` to return `ClearOnDrop<Box<SecretKey<E>>>`.

Change 'NetworkInfo' to use clear-on-drop secret-keys.

---

src/crypto/mod.rs
src/honey_badger.rs
tests/honey_badger.rs

Encryption of proposals in HoneyBadger

---

src/crypto/mod.rs
src/crypto/poly.rs
src/honey_badger.rs
src/messaging.rs
src/sync_key_gen.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_coin.rs
tests/common_subset.rs
tests/honey_badger.rs
tests/network/mod.rs
tests/sync_key_gen.rs

This allows the caller to address nodes by ID instead of by index.
Also contains a few other minor changes that will be needed for
`DynamicHoneyBadger`.

Make SyncKeyGen NodeUid-aware.

---

src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/honey_badger.rs
src/messaging.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_coin.rs
tests/common_subset.rs
tests/network/mod.rs

This allows nodes to join the network without sending any messages
themselves. They can't give any input and just observe the outcome.
Closes #81

Allow observer nodes in all algorithms.

---

src/dynamic_honey_badger.rs
src/honey_badger.rs
src/lib.rs
src/messaging.rs
src/sync_key_gen.rs
tests/dynamic_honey_badger.rs
tests/network/mod.rs
tests/sync_key_gen.rs

`DynamicHoneyBadger` is supposed to allow adding and removing nodes. (See https://github.com/poanetwork/hbbft/issues/47#issuecomment-394640406) Internally, it performs Distributed Key Generation and restarts Honey Badger, but all that should be hidden away from the user.
This is still incomplete in several ways, but removing a node works.

Add DynamicHoneyBadger (part 1).

---

src/common_coin.rs
src/crypto/mod.rs
src/crypto/poly.rs
src/dynamic_honey_badger.rs
src/honey_badger.rs
src/messaging.rs

This precomputes the keys in `NetworkInfo` instead of doing the calculation on every call to `public_key_share`.

Avoid redundant key computations.

---

src/lib.rs

There is no evidence that [optin_builtin_traits](https://doc.rust-lang.org/beta/unstable-book/language-features/optin-builtin-traits.html) are used any longer (the keyword `auto` does not even show up in the codebase).
Removing this features allow compilation on stable Rust 1.27 and possible earlier versions.

Remove unused feature, allowing compilation on stable again.

---

README.md
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/crypto/mod.rs
src/dynamic_honey_badger.rs
src/honey_badger.rs
src/messaging.rs
src/sync_key_gen.rs
tests/dynamic_honey_badger.rs
tests/network/mod.rs

This allows adding and removing full peers to/from the pool of observers.
To allow a joining node to participate in the on-chain key generation, messages are signed and broadcast to all nodes, and the receiver inputs them as transactions.

Add node transaction messages to Dynamic HB.

---

src/crypto/mod.rs
tests/sync_key_gen.rs

I am trying to cut the noise of `let rng = rand::thread_rng(); Foo::random(&mut rng)`, to make tests easier to read and reduce the coupling to a specific RNG, however the API is not well suited to instantiate types that need additional parameters. At least `SecretKey` can (and should) implemented `Rand` here.
Caveats:
* `ThreadRng` in newer versions is marked as cryptographically secure through the `CryptoRng` trait, I do not see any issues in using it. It leverages the OS random generator (which on Linux collects entropy from various sources and adds them to a pool, possibly including real hardware random number generators) and falls back on a generator based on CPU jitter. Said RNG errs on the side of entropy, so it should not be less random, it is simply slower by three to six orders …

Implement `Rand` for `SecretKey`.

---

examples/simulation.rs
src/dynamic_honey_badger.rs
src/honey_badger.rs
tests/honey_badger.rs

This delays handling of messages from epochs that are too far ahead.
Closes #91

Add a max_future_epochs option to Honey Badger.

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
TODO

After talking with folks in several other POA projects I decided to add our own contributing.md file for hbbft. There are not too many projects at this point and each have different testing requirements, pull request templates, languages and other features that make them unique. So, let's make this contributing file work best for this project.   I grabbed some language from other contributing files, feel free to modify as needed. 
Other changes:
- Added standard CODE_OF_CONDUCT file
- Updated TODO file to point to Issues (can possibly delete or repurpose this file)
- Updated README TODOS - Deleted Optimize Coin Algorithm and added adversarial tests. Any additional TODOs that contributors might want to tackle should be added here.

Doc updates: Contributing File, Code of Conduct, README

---

src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/crypto/mod.rs
src/dynamic_honey_badger.rs
src/lib.rs

Also change the signature parity computation, such that every bit is taken into account instead of only the last bit of each byte.
Closes #100

Add module-level Agreement, Coin and Subset documentation.

---

.travis.yml

A small addition to the CI script. It is still a bit tricky to get the exact rustfmt version out of rustup, being able to verify using rustfmt --version helps immensely.

Show `rustfmt` version in CI

---

Cargo.toml

The Rust API guidelines recommend a set of metadata values:
https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-metadata
(See #108)

Add recommended metadata to Cargo.toml

---

examples/simulation.rs
src/dynamic_honey_badger.rs
src/honey_badger.rs
src/lib.rs
src/queueing_honey_badger.rs
src/transaction_queue.rs
tests/honey_badger.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs

This makes Honey Badger a bit more complicated but a lot more flexible:
It is now unaware of transactions and basically just runs one Subset
instance per epoch.
That way, users can use any kind of external queue, control throttling
and prioritization.

Separate queue from Honey Badger.

---

examples/network/node.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/mod.rs
src/honey_badger.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_subset.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs

Replaces `Rc` with `Arc`. This allows usage from different threads
which will be necessary for use with Parity.
The additional runtime performance cost is virtually zero (the tiny extra cost of an atomic read/write is only incurred when cloning/dropping).

Make `*HoneyBadger` types thread safe.

---

src/agreement/bin_values.rs
src/dynamic_honey_badger/votes.rs

Extra lints have been added in the latest version of clippy; this fixes four instances of two of the new lints.
Before:
```
error: this argument is passed by reference, but would be more efficient if passed by value                     
--> src/agreement/bin_values.rs:66:21
|
66 |     pub fn contains(&self, b: bool) -> bool {
|                     ^^^^^ help: consider passing by value instead: `self`
|
= note: `-D trivially-copy-pass-by-ref` implied by `-D clippy`
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.211/index.html#trivially_copy_pass_by_ref
error: this argument is passed by reference, but would be more efficient if passed by value
--> src/agreement/bin_values.rs:76:22
|
76 |     pub fn is_subset(&self, other: BinValues) -> bool {
| …
```

Fix clippy lints.

---

Cargo.toml
examples/simulation.rs
src/agreement/bin_values.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/crypto/mod.rs
src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/mod.rs
src/honey_badger.rs
src/lib.rs
src/queueing_honey_badger.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_coin.rs
tests/common_subset.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs

This branch implements a `RandomAdversary`, which should partially handle #84. Its approach is a bit naive, leveraging two vectors of attack:
1. Replay attacks. These can be implemented automatically, since they require no knowledge of the underlying protocol. With a random probability, the adversary will duplicate a message sent from one node to one of the nodes under its control and broadcast it to all nodes (it could easily be made to select a random correct node instead, but the API makes this a little too cumbersome at the moment. See the comments below for details).
2. Random message generation. At every step of the protocol, the `RandomAdversary` can inject one or more random messages into the network, e.g. setting `p_inject` to `0.10` (10%) will cause one-in-ten steps to create …

Implement a random adversary

---

src/queueing_honey_badger.rs

Needed to retrieve netinfo.
I'm not sure about the name or if we want it to be a permanent method at all but please add this so I don't have to keep cherry-picking it onto my updated branch every day :)

Add QueueingHoneyBadger::dyn_hb.

---

Cargo.toml
src/broadcast.rs
src/crypto/mod.rs
src/dynamic_honey_badger/mod.rs
src/lib.rs
src/messaging.rs
src/sync_key_gen.rs

- Removes the need to wrap `SecretKey`s in `ClearOnDrop<Box<...>>`.
- Allows for stack allocated `SecretKey`s.
- Zeros out the memory occupied by each `SecretKey` on drop.
- Ensures that the clearing of `SecretKey`s is not elided.
- Works on stable.
Closes Issues #89 and #90

Replaced clear-on-drop with 'std::ptr::write_volatile'.

---

.travis.yml

The following changes have been made to the Travis CI:
* The cache timeout has been increased, before builds would spend three minutes trying to cache something before giving up.
* The toolchain for building and testing has been switched to stable. A nightly version is still used to run `clippy` and `rustfmt`; however in both cases the toolchain binaries are used instead of compiling them from scratch.
* The `cargo check` pass has been removed; it simply tested whether or not the crate compiled against stable before compiling again against release. As there very, very few bugs that will cause a mismatch here (differences will be in execution), a trade-off was made in favor of compiling only once.
The CI is currently backed up with jobs for at least another hour or two; hopefully this will …

Tweak CI, now runs stable.

---

src/dynamic_honey_badger/mod.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/queueing_honey_badger.rs

This adds a bit of special handling to make sure messages don't stay in
the queue forever in the `dynamic_honey_badger` tests, even if there is
only one validator: the problem was that the single validator is always
ready for input, so it never processed incoming messages. However, to
add the new validator, it needs to process the joining node's key
generation messages.
`DynamicHoneyBadger` now also removes committed key generation messages
from the queue, to avoid committing duplicates.
Closes #113.

Fix DHB test with 1 validator; purge key gen msgs.

---

examples/simulation.rs
src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/mod.rs
src/queueing_honey_badger.rs
tests/dynamic_honey_badger.rs
tests/queueing_honey_badger.rs

With that, a node can join a running network as an observer in any epoch
where key generation starts.
See #129.

Add a `JoinPlan` to facilitate joining a running DHB network.

---

src/crypto/mod.rs

Just for convenience and consistency. The underlying type (`pairing::bls12_381::G1`, a `[u64; 6]`) already impls. `Copy`.

Add `Copy` to `PublicKey` derived impls.

---

examples/network/node.rs
examples/simulation.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/dynamic_honey_badger/mod.rs
src/fault_log.rs
src/honey_badger.rs
src/messaging.rs
src/queueing_honey_badger.rs
tests/agreement.rs
tests/broadcast.rs
tests/common_coin.rs
tests/common_subset.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs
tests/sync_key_gen.rs

This is a part of the refactoring undertaken to fix #66. It includes:
* the new algorithm output value API,
* integration with the earlier `FaultLog` functionality.
It does not include a new outgoing message API which will be included in a different PR considering the number of files involved in the refactoring and possible work on fixing tests.

Output API refactored

---

.travis.yml
examples/network/node.rs
examples/simulation.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/crypto/mod.rs
src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/honey_badger.rs
src/messaging.rs
src/proto/mod.rs
src/queueing_honey_badger.rs
src/sync_key_gen.rs
tests/broadcast.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs
tests/sync_key_gen.rs

This adds another map of public keys to `NetworkInfo`: It is unsafe to use key _shares_ as keys.
Since creating a new `NetworkInfo` is even more complicated now, `NetworkInfo::generate_map` creates a set of matching instances for testing.
(I also noticed that Clippy wasn't applied to the example, so I added it and fixed the lints.)
Closes #131

Separate keys and key shares.

---

src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/mod.rs
src/fault_log.rs
src/sync_key_gen.rs
tests/sync_key_gen.rs

This adds a "Usage" section to the `sync_key_gen` module and extends some item documentation, too.
The new `SyncKeyGen::into_network_info` method avoids cloning the (non-threshold) keys and helps simplify `DynamicHoneyBadger` a bit.
Finally, `Propose` and `Accept` are renamed to `Part` and `Ack`:
* Structs ideally shouldn't have verbs as their name.
* "`Proposal`"/"`Propose`" suggests that it's a proposal for the actual final keys, but in fact it's just a summand for them. Every node is supposed to contribute a `Part`, and in the ideal case, every node's `Part` will be used.
* "`Ack`" is much shorter than "`Acceptance`" or "`Acknowledgement`".

Extend DKG docs, rename messages, add into_network_info.

---

examples/network/node.rs
src/common_coin.rs
src/crypto/into_fr.rs
src/crypto/mod.rs
src/crypto/poly.rs
src/honey_badger.rs
src/messaging.rs
src/sync_key_gen.rs
tests/sync_key_gen.rs

This removes some unnecessary allocation and conversion by accepting
more primitive types and references as the index in threshold decryption
and signing, and as the argument to a polynomial.
It also adds scalar multiplication, addition and subtraction to `Poly` for convenience.

Accept more types in threshold crypto API.

---

src/agreement/bin_values.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/fault_log.rs
src/messaging.rs

* Don't drop `Term` messages from previous epochs. They are still
relevant for all future epochs.
* Restructure some fields to avoid unnecessary iteration and counting.
* Simplify the fields related to the common coin.
* Reorder the methods, so that the message handlers are all in one
place.
* Handle the case where the coin value arrives before the required
number of `Conf` messages.

Fix agreement bugs, and refactor a few fields.

---

Cargo.toml
examples/network/commst.rs
src/agreement/mod.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/crypto/error.rs
src/crypto/mod.rs
src/dynamic_honey_badger/error.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/honey_badger.rs
src/lib.rs
src/proto_io.rs
src/queueing_honey_badger.rs

* Remove `error_chain` and convert errors to `failure` types.
* Add variants for each possible error generation point.
* Allows the user to programatically determine the precise origin of each error.
* Obviates the need for backtraces. 
* The verbose Error + ErrorKind (E + EK) failure pattern has been used for 'top-level' error-returning modules (`*honey_badger`) as a convenience to the user (it includes backtraces automatically). These are not strictly necessary and the simpler (Error only) pattern could be used instead. The E + EK pattern, though more cumbersome, is also more future-proof and versatile.
* `agreement::Error::HandleCoinCommonCoin`, `TryFinishConfRoundCommonCoin`
* `broadcast::Error::CodingNewReedSolomon`, `CodingEncodeReedSolomon`, 
`CodingReconstructShardsReedSolomon`, …

Replace `chain_error` with `failure`

---

src/honey_badger/batch.rs
src/honey_badger/builder.rs
src/honey_badger/error.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/honey_badger/mod.rs
src/lib.rs

See #121.
This doesn't change any code yet, it only splits up the module (and makes a few fields `pub(super)`).

Split honey_badger into submodules.

---

examples/simulation.rs
src/common_subset.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/fault_log.rs
src/honey_badger/honey_badger.rs
src/queueing_honey_badger.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/queueing_honey_badger.rs

`QueueingHoneyBadger` now waits after an output, and only makes its
proposal for the next epoch when:
* there are pending transactions in the queue,
* there are pending key generation or vote messages, or
* _f + 1_ other validators have already made their proposal.
This rule should work well for small networks: With 1 - 3 nodes, it will
produce a new batch whenever at least one of them has transactions to
contribute. In larger networks, it prevents an adversary controlling _f_
nodes from producing lots of empty epochs.
An exception is made for a currently joining validator: We will commit
up to _(N + 1)² + 1_ key generation messages for them, which is the
maximum number a correct node will send.
Closes #147.

Change the QHB criterion for moving on to the next epoch.

---

src/agreement/bool_multimap.rs
src/agreement/mod.rs
src/agreement/sbv_broadcast.rs

See #175.
Not closing that yet, since there is probably more that could be extracted.

Extract SBV broadcast from agreement.

---

src/agreement/agreement.rs
src/agreement/mod.rs
src/agreement/sbv_broadcast.rs
src/broadcast.rs
src/common_coin.rs
src/common_subset.rs
src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/change.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/fault_log.rs
src/honey_badger/batch.rs
src/honey_badger/builder.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/lib.rs
src/messaging.rs
src/queueing_honey_badger.rs
src/sync_key_gen.rs
src/transaction_queue.rs

* Add the `Contribution`, `NodeUidT`, and `Message` supertraits.
* Rename type parameters:
* `Tx` -> `T` or `C`
* `NodeUid` -> `N`
* I'm not happy with the naming of `NodeUidT`. It technically *could* just be called `NodeUid`, and i'm learning towards just renaming it back to that, but it does share a name with `DistAlgorithm::NodeUid`. This is allowed but seems like it could be slightly confusing. Maybe not.
* Also the `traits` module name isn't wonderful.
As usual, It takes as more effort to name things as it does to code them...
@mbr, @afck, @drPeterVanNostrand, @vkomenda: Please let me know what you guys think.

Add common supertraits and rename related type parameters.

---

src/honey_badger/epoch_state.rs
src/honey_badger/honey_badger.rs
src/threshold_decryption.rs

* Remove unnecessary recursive method calls.
* Add `handle_message` (without the trait).
* Fix a bug where `handle_message_content` would create an `EpochState`
with the wrong number.
* Move a few `match` statements from `EpochState` to `SubsetState`.

Fix and clean up the HoneyBadger impl.

---

.travis.yml
examples/network/node.rs
examples/simulation.rs
src/broadcast/mod.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/error.rs
src/dynamic_honey_badger/votes.rs
src/fault_log.rs
src/messaging.rs
src/sync_key_gen.rs
tests/broadcast.rs
tests/network/mod.rs
tests/sync_key_gen.rs

- Adds error handling around errors that could arise from failed `mlock`/`munlock` syscalls.
Closes Issue #165

Added error handling for mlock errors in threshold_crypto crate.

---

tests/dynamic_honey_badger.rs

The Dynamic Honey Badger tests would currently fail _without_ faulty
nodes, because with "first" delivery, all but the first _N - f_ nodes
are lagging indefinitely.
This change makes sure we give lagging nodes a chance to finish the first
phase of the test and arrive at the batch containing the completed
`Remove` event.

Fix DHB test: wait for lagging nodes.

---

.travis.yml

~~Do not pull this yet and be very, very quiet; I'm trying to tease out a `SIGILL`.~~
I cut it short and created one, to ensure it works: https://travis-ci.org/poanetwork/hbbft/builds/415424600
The `after_failure` block will print the last 250 lines of the the syslog, which should contain information about the `SIGILL`.
Unfortunately it also adds a `sudo` dependency; travis analyses CI configurations beforehand and runs those that require `sudo` on VMs instead of containers. As a result there's a ~40 second startup time.

`SIGILL` on travis

---

README.md
src/broadcast/broadcast.rs
src/broadcast/mod.rs
src/lib.rs
src/subset.rs
tests/subset.rs

* Make the `merkle` module private.
* Make sure the algorithm names are consistent.
* Add the Threshold Decryption and Synchronous Key Generation algorithms
to the list in the main crate documentation.
* Remove some trailing whitespace from the README.
* Remove checkboxes: all algorithms are implemented.
* Link to the algorithm implementations, not the modules.
* Use relative links in the README.
Closes #100.

Update docs: missing algorithms, private merkle, whitespace.

---

.travis.yml
examples/network/connection.rs
examples/network/node.rs
examples/simulation.rs
src/broadcast/broadcast.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/votes.rs
src/honey_badger/epoch_state.rs
src/subset.rs
src/sync_key_gen.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/net/mod.rs
tests/sync_key_gen.rs

For the planned migration to Rust 1.29, switch the CI over to the now working beta (tested with `rustc 1.29.0-beta.7 (49720ea9c 2018-08-26)`). The following advance to 1.29 should ideally be seamless afterwards.

Advance to Rust beta

---

examples/simulation.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/error.rs
src/honey_badger/builder.rs
src/honey_badger/epoch_state.rs
src/honey_badger/error.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/subset.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/net_dynamic_hb.rs
tests/queueing_honey_badger.rs

This PR adds a basic part of the spam protection functionality according to #43. The following are added:
1. a map of known `HoneyBadger` epochs of remote `HoneyBadger` nodes;
2. a message broadcast to all remote nodes signalling the start of an epoch;
3. a step output from the builders of `HoneyBadger`, `DynamicHoneyBadger` and `QueueingHoneyBadger`, with the necessary adjustments in tests and in the simulation.
The tests now pass and the PR is ready for review.

Spam protection part 1: remote epoch tracking in HoneyBadger

---

tests/net/adversary.rs
tests/net/mod.rs

This PR adds the API for adversaries that (hopefully) restricts them to capabilities listed in the hbbft paper by wrapping all references in wrappers that enforce these invariants. Ideally, this should be free (except for the additional tests), at least in `--release` mode.
The resulting API will hopefully prove ergonomic. I also smuggled in another adversary implementation, which is a one-liner simulating the previous test-framework's behavior.

Adversary traits

---

.travis.yml

This is off by default so that binaries can be shared. Enabling this
flag could improve test speed on Travis (will check).

Travis: Enable cpu-specific optimizations.

---

.travis.yml

Currently, Clippy is a mess on travis and elsewhere, with the switch from beta to stable adding in numerous other problems. This PR disables it until we decide whether to reenable it fully, partially or not at all after pinning stable.

Temporarily disable clippy.

---

Cargo.toml
tests/net/proptest.rs

When run with `--release`, `cargo test` will use `[profile.bench]` to compile the crate itself, but all dependencies use `[profile.release]`. This is both an excellent trap to fall into and a nifty default to exploit when one is aware of the fact.
The PR fixes a bug that made it through (`!` is both logical and bitwise negation in Rust) but would have been caught by overflow checks, and enables these checks even for `--release` tests (but not builds).
After careful benchmarking, the `[profile.release]` was not altered due to the performance being noticeably worse when `overflow-checks` are added there. There might be some merit in adding them in the `[profile.bench]` section in `threshold_crypto` as well, provided the tests are smaller.
CC'ing @afck for the heads-up!

Enable overflow-checks and fix a bug that slipped through during their absence.

---

tests/README.md
tests/net/err.rs
tests/net/mod.rs

Adds a wall-clock time limit to virtual networks, the default is 20 minutes. It can be changed or disabled in a variety of ways.
Briefly tested, but not unit tests at the moment (a generic testing-`DistAlgorithm` is still missing). The merge should be squashed.

Add a test time limit.

---

tests/net/mod.rs

Until we arrive at a better solution, this should at least give us some output when a test hangs.

Change the time limit to five minutes for now.

---

.travis.yml

`cargo install` fails if it's already installed.

Fix build failure if deadlinks is already installed.

---

src/dynamic_honey_badger/builder.rs
src/honey_badger/builder.rs
src/honey_badger/epoch_state.rs
src/honey_badger/honey_badger.rs
src/honey_badger/mod.rs

Fixes #243. Allow client code to control the behavior of `EpochState` and when it decides to send decryption shares. There are two options for the behavior for handling the output of a `Subset` algorithm, which are represented by the new `SubsetHandlingStrategy` (bikeshedding welcome!) enum:
1) `Incremental`, which is the current (optimized) behavior.
2) `AllAtEnd`, which is supposed to be the old behavior. *Reviewers crunched for time might want to place priority on making sure I've done this right.*
`SubsetHandlingStrategy` is exposed at the builder level. Internally, an `EpochState` instance now stores a `SubsetHandler` enum member that models the necessary state for each different strategy. To resolve ownership issues, I've changed …

Make Subset optimization optional

---

Cargo.toml
tests/README.md
tests/net/mod.rs
tests/net/proptest.rs
tests/net_dynamic_hb.rs
tests/net_util.proptest-regressions
tests/net_util.rs

Replaces the `NetworkDimensionStrategy`'s implementation with one based on a mapping of network dimensions to the natural numbers. This fixed panics during shrinking, making tests not exit without information when failing.

Fix test-case shrinking issues

---

src/coin.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/honey_badger/honey_badger.rs
src/messaging.rs
src/util.rs

Using `hbbft` in other software that is based on frameworks like [tokio](https://tokio.rs), being `Send` is often a requirement on shared data structures.
This goes slightly beyond just making sure HoneyBadger is suitable for tokio by adding a `Send` requirement on `DistAlgorithm`. It was tempting to do so and ensures we won't accidentally break things in the future at the cost of complicating `coin.rs` slightly; we can restrict to just adding the `Box<Rng + Send>` type bounds instead if this is an issue.

Make `DistAlgorithm` require `Send`.

---

examples/consensus-node.rs
examples/simulation.rs
src/dynamic_honey_badger/batch.rs
tests/binary_agreement.rs
tests/broadcast.rs
tests/coin.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/queueing_honey_badger.rs
tests/subset.rs
tests/sync_key_gen.rs

Pairing isn't used directly in tests and examples anymore.
Also, use the new `Iterator::flatten`.

Remove unused pairing imports.

---

examples/simulation.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/error.rs
src/honey_badger/builder.rs
src/honey_badger/error.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/subset.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/net_dynamic_hb.rs
tests/queueing_honey_badger.rs

This reverts PR #219 and simplifies the code a bit. We need an external sender queue (#226) that would manage epoch announcements by itself. `EpochStarted` messages from algorithms will not be used. Hence I've removed those.

Revert EpochStarted messages

---

src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
tests/dynamic_honey_badger.rs
tests/net/mod.rs
tests/net_dynamic_hb.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs

Instead of just the public key, the batches returned from `DynamicHoneyBadger` and `QueueingHoneyBadger` now contain the full `NetworkInfo`, so the user can use the validators' keys for signing and encryption.

Add `NetworkInfo` to `Batch`.

---

examples/simulation.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/queueing_honey_badger.rs
src/transaction_queue.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/queueing_honey_badger.rs

Transaction queue is the component in old tests which is not currently tested by `proptest`-based tests. This PR adds functionality which enables such tests with a given random seed.
Only the minimal support is provided in the old non-`proptest` based tests, the intention being to extend the new framework wherever possible.

Support a global RNG in transaction queue

---

src/queueing_honey_badger.rs
src/transaction_queue.rs

Small change to shrink the interface of `TransactionQueue` by leveraging `iter::once`. We only use `push` once anyway. The resulting generated .asm should be for all intents and purposes identical.

Remove push from queue

---

src/binary_agreement/binary_agreement.rs
src/binary_agreement/mod.rs
src/broadcast/broadcast.rs
src/broadcast/mod.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/queueing_honey_badger.rs
src/subset.rs
src/sync_key_gen.rs
src/threshold_decryption.rs
src/threshold_sign.rs

Extends all APIs so that the user doesn't need to import the
`DistAlgorithm` trait.
Also, removes the error on inputting too late into `BinaryAgreement`:
whether the input still matters is an implementation detail.

Extend API to work without DistAlgorithm.

---

src/subset.rs

Fixes #282 
Let me know if you think a specialized test is needed. This bug is only covered by tests in https://github.com/poanetwork/hbbft/tree/vk-extern-sender-queue. It should be possible to trigger the bug (and the fault) by sending _some_ `Aux` messages before the corresponding `Proof` messages, so that `Agreement` instances finish before _some_ `Broadcast` instances.

Fixed early output from Subset

---

README.md

The Binary Agreement is mostly referred to as "ABA" in the [paper](https://eprint.iacr.org/2016/199.pdf).
(Unfortunately not consistently: the box with the message flow just says "BA".)

Fix abbreviations from the paper: ABA.

---

src/subset.rs
tests/net/proptest.rs

The `NetworkDimension` should not go below `min_size`.
The `Subset` problem was that if we received the `BinaryAgreement` result _first_, then when receiving the `Broadcast` output, `process_binary_agreement` wouldn't call `try_binary_agreement_completion` anymore, and never output.

Fix minimal NetworkDimension in tests, and Subset bug.

---

src/binary_agreement/sbv_broadcast.rs
src/threshold_decryption.rs

Make sure observers also try to output when receiving a `BVal` message.
Also, make sure `ThresholdDecryption` doesn't fail for observers without
a key share.

Fix SbvBroadcast observer issue.

---

src/binary_agreement/binary_agreement.rs
src/binary_agreement/mod.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/honey_badger/builder.rs
src/honey_badger/epoch_state.rs
src/honey_badger/honey_badger.rs
src/lib.rs
src/network_info.rs
src/subset.rs
src/traits.rs
tests/binary_agreement.rs
tests/subset.rs

This change also fixes a subtle security issue: We were potentially reusing the same coins in some rare cases!
If we are in epoch 41 and are just about to e.g. finish voting on a change, and `max_future_epochs == 2`, an attacker might send contributions for epochs 42 and 43 in the current (old) `HoneyBadger` instance. This would trigger the other nodes to start corresponding `BinaryAgreement`s and potentially flip "HB epoch 42" and "43" coins in them.
Once epoch 41 actually concludes, everyone starts a new `HoneyBadger` instance in epoch 42, where the same coins will be flipped again, and the attacker now knows a few values in advance.
That's probably not critical at all, but it's now addressed: We include the `start_epoch` in the coin name.

Make the BA session ID generic.

---

src/binary_agreement/mod.rs
tests/binary_agreement_mitm.rs
tests/net/adversary.rs
tests/net/mod.rs

Add a test for the reordering attack on BinaryAgreement

---

src/broadcast/broadcast.rs
src/subset.rs

Specifically, we don't have plans at the moment to move serialization into `Subset` and `Broadcast`: It doesn't make sense to force serde on the user, and often there's e.g. additional encryption involved. Our algorithms shouldn't care about that, and just take a `Vec<u8>`.

Remove some obsolete TODOs and comments.

---

Cargo.toml

This disables SIMD in reed-solomon-erasure to work around problems on Android.
Closes #317.
See #214.

Add a no-simd feature.

---

src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/change.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs
src/fault_log.rs
src/honey_badger/builder.rs
src/honey_badger/epoch_state.rs
src/honey_badger/error.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/lib.rs
src/threshold_decrypt.rs
tests/honey_badger.rs

This is a very simple rename.
Closes #326.

Rename `ThresholdDecryption` to `ThresholdDecrypt`

---

src/binary_agreement/binary_agreement.rs
src/binary_agreement/mod.rs
src/binary_agreement/sbv_broadcast.rs
src/fault_log.rs
tests/binary_agreement_mitm.rs

Closes #43 
This is the second and last part of #43. In includes
- limitation on the number of future Binary Agreement epochs for which we accept and queue messages from remote nodes;
- finite representation of incoming messages in a future epoch.

Make the incoming message queue finite in Binary Agreement

---

src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/builder.rs
src/dynamic_honey_badger/change.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs
src/fault_log.rs
src/honey_badger/batch.rs
src/honey_badger/builder.rs
src/honey_badger/epoch_state.rs
src/honey_badger/error.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/honey_badger/mod.rs
src/threshold_decrypt.rs
tests/honey_badger.rs

This includes a threshold signature in each batch that can be used as a pseudorandom value.
Also moves `EncryptionSchedule` from `threshold_decrypt` to `honey_badger`, and adds both encryption schedule and random value to the test.
See #183.

Add a random_value option to HB and DHB.

---

src/dynamic_honey_badger/batch.rs
src/dynamic_honey_badger/change.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/queueing_honey_badger/mod.rs
src/sender_queue/dynamic_honey_badger.rs
src/sender_queue/honey_badger.rs
src/sender_queue/mod.rs
src/sender_queue/queueing_honey_badger.rs
src/sync_key_gen.rs
tests/dynamic_honey_badger.rs
tests/net_dynamic_hb.rs
tests/network/mod.rs
tests/queueing_honey_badger.rs

This replaces `NodeChange` with a full list of IDs and public keys, instead of just a single to-be-added or to-be-removed node, to allow completely replacing the set of validators by any arbitrary new set in a single key generation step.
Closes #330.

Allow arbitrary validator set changes in DHB.

---

src/dynamic_honey_badger/builder.rs
src/honey_badger/builder.rs
src/honey_badger/honey_badger.rs
src/honey_badger/mod.rs
src/honey_badger/params.rs

This removes some duplication between DHB, HB and their builders.
See #333.

Add a `Params` struct with HB parameters.

---

tests/binary_agreement.rs

In the process of updating the BA test I had to remove the observer check temporarily from that test until we implement observers in the test framework. See #322.
I also removed logging from the test in advance of `EventLog`, see #335.

Binary Agreement test updated to the proptest framework

---

src/sync_key_gen.rs

Not only is the code simpler this way, it also has the advantage that a node that has crashed and is restarting can recompute its key share.

Keep key gen msgs with values encrypted to self. Remove TODO.

---

src/honey_badger/honey_badger.rs

We are going to need this if we use `HoneyBadger` directly, to replace `DynamicHoneyBadger::should_propose`.

Make received_proposals public.

---

Cargo.toml
examples/network/commst.rs
examples/network/messaging.rs
examples/network/node.rs

This solves the vulnerability lint which affects the previously used version 0.3.2 of `crossbeam`. The changes only affect the old test.

Update the crossbeam dependency to 0.5

---

src/fault_log.rs
tests/binary_agreement.rs
tests/binary_agreement_mitm.rs
tests/net/err.rs
tests/net/mod.rs
tests/net_dynamic_hb.rs

See #120.
Tests will fail if there is a step with a fault report referring to a correct node. This PR also adds storage for the fault log in the test node struct alongside output storage.

Added fault checking on every step in the net framework

---

examples/simulation.rs
src/broadcast/broadcast.rs
src/dynamic_honey_badger/votes.rs
src/honey_badger/honey_badger.rs
src/queueing_honey_badger/mod.rs
src/threshold_decrypt.rs
src/threshold_sign.rs
src/traits.rs
tests/queueing_honey_badger.rs

Also make `Step::extend_with` `#[must_use]`, so the user doesn't forget to handle the output.

Remove unwrap and expect calls from production code.

---

src/dynamic_honey_badger/dynamic_honey_badger.rs
src/sender_queue/dynamic_honey_badger.rs
src/sender_queue/error.rs
src/sender_queue/mod.rs
src/sender_queue/queueing_honey_badger.rs
src/traits.rs
tests/net/err.rs
tests/net/mod.rs
tests/net_dynamic_hb.rs

Fixes #369.
The fix mostly amounts to improving how removed nodes are handled in `VirtualNet`.
The sender queue algorithm now flags itself if it was removed. The user can check the flag `is_removed` to shut down the node.

Fixes the net_dynamic_hb test

---

examples/network/node.rs
examples/simulation.rs
src/binary_agreement/binary_agreement.rs
src/broadcast/broadcast.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs
src/fault_log.rs
src/honey_badger/honey_badger.rs
src/lib.rs
src/queueing_honey_badger/mod.rs
src/sender_queue/dynamic_honey_badger.rs
src/sender_queue/honey_badger.rs
src/sender_queue/mod.rs
src/sender_queue/queueing_honey_badger.rs
src/subset/subset.rs
src/threshold_decrypt.rs
src/threshold_sign.rs
src/traits.rs
tests/README.md
tests/binary_agreement.rs
tests/binary_agreement_mitm.rs
tests/broadcast.rs
tests/honey_badger.rs
tests/net/adversary.rs
tests/net/err.rs
tests/net/mod.rs
tests/network/mod.rs

Rename DistAlgorithm to ConsensusProtocol.

---

examples/network/commst.rs
src/binary_agreement/binary_agreement.rs
src/binary_agreement/bool_multimap.rs
src/broadcast/broadcast.rs
src/broadcast/message.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/honey_badger/epoch_state.rs
src/lib.rs
src/subset/subset.rs
src/sync_key_gen.rs
src/threshold_sign.rs
src/util.rs
tests/binary_agreement_mitm.rs
tests/net/adversary.rs
tests/net/err.rs
tests/net/mod.rs
tests/network/mod.rs

Apply `cargo fix --edition-idioms`.

Use Rust 2018 idioms consistently.

---

src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs

related to issue #381 
Makes possible to get an immutable reference to the `HoneyBadger` contained in a `DynamicHoneyBadger`

Add `honey_badger` getter for `DynamicHoneyBadger`

---

src/sync_key_gen.rs
tests/net_dynamic_hb.rs

`SyncKeyGen` should tolerate duplicate `Part` messages as long as they are identical.
The `drop_and_re_add` test had an arithmetic overflow, because it tried to remove more faulty nodes than nodes in total.
I also renamed `shutdown_epoch` to `re_add_epoch` in the test, because that's what it seems to actually do.

Fix a SyncKeyGen and a DHB test issue.

---

src/sender_queue/mod.rs
tests/net_dynamic_hb.rs

If a previously removed peer gets added back as a validator, `SenderQueue` now removes that peer from `last_epochs`, so it doesn't drop it later.
(Also minor cleanups in the `net_dynamic_hb` test module.)
Closes #390.

Don't drop re-added peers from sender queue.

---

.travis.yml
Cargo.toml
examples/simulation.rs
src/binary_agreement/bool_set.rs
src/binary_agreement/mod.rs
src/binary_agreement/sbv_broadcast.rs
src/broadcast/merkle.rs
src/broadcast/message.rs
src/dynamic_honey_badger/change.rs
src/dynamic_honey_badger/mod.rs
src/dynamic_honey_badger/votes.rs
src/honey_badger/epoch_state.rs
src/honey_badger/honey_badger.rs
src/honey_badger/message.rs
src/honey_badger/params.rs
src/sender_queue/message.rs
src/subset/message.rs
src/subset/subset.rs
src/sync_key_gen.rs
src/threshold_decrypt.rs
src/threshold_sign.rs

This addresses the problem in poanetwork/threshold_crypto#78. The `threshold_crypto` dependency in this PR needs to be changed after `threshold_crypto` 0.3.1 is uploaded to crates.io.

Use the serde derive feature and update other dependencies

---

src/binary_agreement/binary_agreement.rs
src/binary_agreement/sbv_broadcast.rs

Binary agreement erroneously kept handling queued incoming messages for an epoch `n`, even if during the handling, the epoch was incremented to `n + 1`. This caused `DuplicateAux` faults in the tests, but it could potentially break consensus.
Closes #392.

Fix BA message handling on epoch change.

---

examples/network/messaging.rs
examples/simulation.rs
hbbft_testing/src/lib.rs
src/broadcast/broadcast.rs
src/broadcast/error.rs
src/broadcast/merkle.rs
src/broadcast/message.rs
src/broadcast/mod.rs
src/messaging.rs
src/network_info.rs
src/traits.rs

Optimized broadcast #309

---

.travis.yml
README.md
ci.sh
examples/simulation.rs
src/honey_badger/honey_badger.rs
src/network_info.rs
tests/dynamic_honey_badger.rs
tests/honey_badger.rs
tests/queueing_honey_badger.rs

This also disables `cargo audit` until #415 is fixed.
Closes #413.

Add HoneyBadger::skip_to_epoch and NetworkInfo::other_ids.

---

.travis.yml
Cargo.toml
ci.sh
examples/network/messaging.rs
examples/simulation.rs
hbbft_testing/Cargo.toml
hbbft_testing/src/lib.rs
src/binary_agreement/binary_agreement.rs
src/binary_agreement/sbv_broadcast.rs
src/broadcast/broadcast.rs
src/broadcast/mod.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/dynamic_honey_badger/mod.rs
src/messaging.rs
src/sender_queue/mod.rs
src/threshold_decrypt.rs
src/threshold_sign.rs
src/traits.rs
tests/honey_badger.rs

`Target` now only has a `Nodes` and an `AllExcept` variant, to specify
a message's target via a whitelist or blacklist. This avoids cloning
the message content and simplifies the code in several places.
Closes #408, closes #415.

Change the `Target` variants.

---

hbbft_testing/src/lib.rs
src/broadcast/broadcast.rs

This guarantees that the sender's own ID is never included in the `Target`: neither in `Nodes`, nor in the exclusions in `AllExcept`. Messages are never meant to be handled by the sender.

Test that self is always omitted from Target.

---

src/sync_key_gen.rs

When gathering Part and Ack messages I repeatedly ran into the situation where I needed to access the "sender" with the messages returned by `handle_part()` and `handle_ack()`. 
Without the ability to query the "our_id" member of SyncKeyGen directly that information had to be tediously tracked along with the collection of SyncKeyGen instances, complicating the code unnecessarily.

Added accessor to "our_id" for SyncKeyGen

---

.travis.yml
Cargo.toml
examples/network/node.rs
examples/simulation.rs
hbbft_testing/src/proptest.rs
src/broadcast/broadcast.rs
src/dynamic_honey_badger/dynamic_honey_badger.rs
src/queueing_honey_badger/mod.rs
tests/broadcast.rs
tests/queueing_honey_badger.rs
tests/subset.rs
tests/threshold_sign.rs

QHB needs to remove the output from the queue, even if it's during a `propose` call. In the case of a single validator, the `propose` call always immediately outputs, so forgetting about this caused an infinite loop.
The QHB test is extended to the case of 2 validators, which also tests a single one, since the QHB test removes and re-adds one of its validators.
Closes #432

Fix QHB loop with 1 validator.
